version: '3.8'

services:
  db:
    image: postgres:14.15
    container_name: region-db
    environment:
      POSTGRES_DB: regionDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    networks:
      - region-network

  region-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: region-service
    ports:
      - '8081:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - db
    networks:
      - region-network

networks:
  region-network:
    driver: bridge