version: '3.8'

services:
  db:
    image: postgres:14.15
    container_name: region-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: regionDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    networks:
      - region-network

  wallet-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: region-service
    ports:
      - '8081:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5434/regionDb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db
    networks:
      - region-network

networks:
  wallet-network:
    driver: bridge