spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/regionDb
    username: postgres
    password: root
  liquibase:
    change-log: classpath:liquibase/changelog-master.yaml
server:
  port: 8080
repoImpl: jpa


